[platformio]
default_envs = esp32c3_a0090_servo_test
src_dir = firmware/esp32c3_a0090_servo_test

[env:esp32c3_a0090_servo_test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  madhephaestus/ESP32Servo@^3.0.6
